// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzgrIxOqbH8ZdHWVlwLue2c4Qe04IdRuo',
    appId: '1:737798087898:android:46638416251aa7fffb31e3',
    messagingSenderId: '737798087898',
    projectId: 'flutter-bloc-flutterando',
    storageBucket: 'flutter-bloc-flutterando.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOTsl2zi9WOdW5BRY6Cy1yd3tZD9dsRik',
    appId: '1:737798087898:ios:5f14e84b72bd0c4bfb31e3',
    messagingSenderId: '737798087898',
    projectId: 'flutter-bloc-flutterando',
    storageBucket: 'flutter-bloc-flutterando.firebasestorage.app',
    iosClientId: '737798087898-d3o4tp7k88c38fd0570tpgn8p47a598r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMobileChallenge',
  );
}
